// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart/internal/repository (interfaces: DatabaseRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mocks_database.go -package=mocks gophermart/internal/repository DatabaseRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "gophermart/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseRepository is a mock of DatabaseRepository interface.
type MockDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRepositoryMockRecorder
	isgomock struct{}
}

// MockDatabaseRepositoryMockRecorder is the mock recorder for MockDatabaseRepository.
type MockDatabaseRepositoryMockRecorder struct {
	mock *MockDatabaseRepository
}

// NewMockDatabaseRepository creates a new mock instance.
func NewMockDatabaseRepository(ctrl *gomock.Controller) *MockDatabaseRepository {
	mock := &MockDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRepository) EXPECT() *MockDatabaseRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockDatabaseRepository) CreateOrder(order models.Order) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", order)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockDatabaseRepositoryMockRecorder) CreateOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockDatabaseRepository)(nil).CreateOrder), order)
}

// CreateUser mocks base method.
func (m *MockDatabaseRepository) CreateUser(user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDatabaseRepositoryMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDatabaseRepository)(nil).CreateUser), user)
}

// GetOrderByNumber mocks base method.
func (m *MockDatabaseRepository) GetOrderByNumber(number string) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", number)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockDatabaseRepositoryMockRecorder) GetOrderByNumber(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockDatabaseRepository)(nil).GetOrderByNumber), number)
}

// GetOrdersByUserLogin mocks base method.
func (m *MockDatabaseRepository) GetOrdersByUserLogin(login string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserLogin", login)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserLogin indicates an expected call of GetOrdersByUserLogin.
func (mr *MockDatabaseRepositoryMockRecorder) GetOrdersByUserLogin(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserLogin", reflect.TypeOf((*MockDatabaseRepository)(nil).GetOrdersByUserLogin), login)
}

// GetUserBalance mocks base method.
func (m *MockDatabaseRepository) GetUserBalance(login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockDatabaseRepositoryMockRecorder) GetUserBalance(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockDatabaseRepository)(nil).GetUserBalance), login)
}

// GetUserByLogin mocks base method.
func (m *MockDatabaseRepository) GetUserByLogin(login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockDatabaseRepositoryMockRecorder) GetUserByLogin(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockDatabaseRepository)(nil).GetUserByLogin), login)
}

// GetWithdrawalsByUserLogin mocks base method.
func (m *MockDatabaseRepository) GetWithdrawalsByUserLogin(login string) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserLogin", login)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserLogin indicates an expected call of GetWithdrawalsByUserLogin.
func (mr *MockDatabaseRepositoryMockRecorder) GetWithdrawalsByUserLogin(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserLogin", reflect.TypeOf((*MockDatabaseRepository)(nil).GetWithdrawalsByUserLogin), login)
}

// WithdrawBalance mocks base method.
func (m *MockDatabaseRepository) WithdrawBalance(login, orderNumber string, sum float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBalance", login, orderNumber, sum)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBalance indicates an expected call of WithdrawBalance.
func (mr *MockDatabaseRepositoryMockRecorder) WithdrawBalance(login, orderNumber, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBalance", reflect.TypeOf((*MockDatabaseRepository)(nil).WithdrawBalance), login, orderNumber, sum)
}
