version: "3"

tasks:
  up:
    desc: "Podman compose up"
    cmds:
      - podman compose -f docker-compose.yaml up --detach
  
  down:
    desc: "Podman compose down"
    cmds:
      - podman compose -f docker-compose.yaml down
